# Generated by Django 4.2.1 on 2023-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.CharField(max_length=30),
        ),
    ]
